### ISSUE TITLE
nukes cause crash when destroying multiblocks

### ISSUE THREAD

**Issue by anonymousomeone** [anonymousomeone/Hbm-s-Nuclear-Tech-GIT#10]
```java
[19:16:54] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.World.isOutsideBuildHeight(World.java:225) ~[amu.class:?]
	at net.minecraft.world.World.getBlockState(World.java:905) ~[amu.class:?]
	at net.minecraft.world.World.destroyBlock(World.java:403) ~[amu.class:?]
	at com.hbm.blocks.machine.DummyBlockAssembler.breakBlock(DummyBlockAssembler.java:45) ~[DummyBlockAssembler.class:2.0.2]
	at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:567) ~[axw.class:?]
	at net.minecraft.world.World.setBlockState(World.java:343) ~[amu.class:?]
	at net.minecraft.world.World.setBlockState(World.java:425) ~[amu.class:?]
	at com.hbm.explosion.ExplosionNukeRayBatched.processChunkBlocks(ExplosionNukeRayBatched.java:239) ~[ExplosionNukeRayBatched.class:2.0.2]
	at com.hbm.explosion.ExplosionNukeRayBatched.processChunk(ExplosionNukeRayBatched.java:210) ~[ExplosionNukeRayBatched.class:2.0.2]
	at com.hbm.entity.logic.EntityNukeExplosionMK5.TickCentral_TrueOnUpdateTick(EntityNukeExplosionMK5.java:124) ~[EntityNukeExplosionMK5.class:2.0.2]
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56) ~[TickHub.class:3.2]
	at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:105) ~[LagGoggles-1.12.2-5.9-140.jar:1.12.2-5.9-140]
	at com.hbm.entity.logic.EntityNukeExplosionMK5.onUpdate(EntityNukeExplosionMK5.java) ~[EntityNukeExplosionMK5.class:2.0.2]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1762) ~[amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by anonymousomeone** [comment]
ok world corruption
```
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// There are four lights!
Time: 2024-10-26 19:22:01 PDT
Description: Ticking entity
java.lang.NullPointerException: Ticking entity
    at net.minecraft.world.World.isOutsideBuildHeight(World.java:225)
    at net.minecraft.world.World.getBlockState(World.java:905)
    at net.minecraft.world.World.destroyBlock(World.java:403)
    at com.hbm.blocks.machine.DummyBlockAssembler.breakBlock(DummyBlockAssembler.java:45)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:567)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.world.World.setBlockState(World.java:425)
    at com.hbm.explosion.ExplosionNukeRayBatched.processChunkBlocks(ExplosionNukeRayBatched.java:239)
    at com.hbm.explosion.ExplosionNukeRayBatched.processChunk(ExplosionNukeRayBatched.java:210)
    at com.hbm.entity.logic.EntityNukeExplosionMK5.TickCentral_TrueOnUpdateTick(EntityNukeExplosionMK5.java:124)
    at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56)
    at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:105)
    at com.hbm.entity.logic.EntityNukeExplosionMK5.onUpdate(EntityNukeExplosionMK5.java)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
No Mixin Metadata is found in the Stacktrace.
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Entity being ticked --
  Entity Type: hbm:entity_nuke_mk5 (com.hbm.entity.logic.EntityNukeExplosionMK5)
  Entity ID: 3
  Entity Name: entity.entity_nuke_mk5.name
  Entity's Exact location: -525.63, 63.50, -327.38
  Entity's Block location: World: (-526,63,-328), Chunk: (at 2,3,8 in -33,-21; contains blocks -528,0,-336 to -513,255,-321), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  ```
